# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [1]:
import  numpy as np

house_sqm=[45,72,64,89,70,100,95,84,77,93]
rooms=[1,3,2,3,3,4,4,3,3,4]
prices=[150000,200000,170000,210000,190000,310000,280000,240000,180000,290000]

house_features=np.array([house_sqm,rooms,prices])

print("squaremeter of house:\n",house_sqm)
print("rooms:\n",rooms)
print("prices:\n",prices)

print("house features:\n",house_features)


squaremeter of house:
 [45, 72, 64, 89, 70, 100, 95, 84, 77, 93]
rooms:
 [1, 3, 2, 3, 3, 4, 4, 3, 3, 4]
prices:
 [150000, 200000, 170000, 210000, 190000, 310000, 280000, 240000, 180000, 290000]
house features:
 [[    45     72     64     89     70    100     95     84     77     93]
 [     1      3      2      3      3      4      4      3      3      4]
 [150000 200000 170000 210000 190000 310000 280000 240000 180000 290000]]


2. Transpose the array you have created, so that every line can represent features of one house.

In [2]:
hf=house_features.T

print("house_features:\n   sqm      rooms price \n",hf)

house_features:
   sqm      rooms price 
 [[    45      1 150000]
 [    72      3 200000]
 [    64      2 170000]
 [    89      3 210000]
 [    70      3 190000]
 [   100      4 310000]
 [    95      4 280000]
 [    84      3 240000]
 [    77      3 180000]
 [    93      4 290000]]


3. Display the shape of the array and explain what it means.

In [3]:
print("shape of array: ", house_features.shape )
print("\t"*2, " ^   ^")
print("\t"*2, " |   |")
print("\t"*2, "rows columns")

print("-"*100)
print("each row stores an house different feature. There are 10 house (column count)")

shape of array:  (3, 10)
		  ^   ^
		  |   |
		 rows columns
----------------------------------------------------------------------------------------------------
each row stores an house different feature. There are 10 house (column count)


4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [9]:
import  numpy as np

row_number=int(input("Enter row number"))
column_number=int(input("Enter column number"))

if row_number>0 and column_number>0: 
    array1=np.ones([row_number,column_number])

    for r in range(row_number):
        for c in range(column_number):
            if (c+1)%2==0 and (r+1)%2==0:
                array1[r][c]=0

    print(array1)
else:
    print("error!")
    

    

Enter row number 8
Enter column number 7


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1.]]
