# <font color=blue>Assignments for "Indexing and Slicing of NumPy Arrays"</font>

For the assignment, you are going to use [Earthquakes](https://www.kaggle.com/kmlyldrn/earthquakes/download/izOLQTcLOKRObsmtrLQO%2Fversions%2FPznRtsl5ks4QmYg3QZhQ%2Ffiles%2FEarthquakes.csv?datasetVersionNumber=2) dataset.

1. Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [5]:
import numpy as np

data=np.loadtxt("Earthquakes.csv",delimiter=",")

print(data)

[[0.000e+00 0.000e+00 0.000e+00 ... 4.000e+00 7.000e+00 0.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 ... 4.100e+00 7.000e+00 0.000e+00]
 [2.000e+00 0.000e+00 0.000e+00 ... 4.400e+00 7.000e+00 0.000e+00]
 ...
 [6.571e+03 4.000e+00 0.000e+00 ... 4.800e+00 2.000e+00 0.000e+00]
 [6.572e+03 3.000e+00 0.000e+00 ... 5.200e+00 2.000e+00 0.000e+00]
 [6.573e+03 2.000e+00 0.000e+00 ... 4.400e+00 2.000e+00 0.000e+00]]


2. Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [6]:
data1= data[0:20,[3,5,7,12]]

print(data1)


[[ 0.     36.8578 16.97    4.    ]
 [ 0.     37.4341  7.02    4.1   ]
 [ 0.     37.6878 10.27    4.4   ]
 [ 0.     37.2003 78.07    4.    ]
 [ 0.     35.6846 42.77    4.5   ]
 [ 0.     36.4171 14.86    4.1   ]
 [ 0.     36.0535 36.68    5.2   ]
 [ 0.     37.1958 50.33    4.8   ]
 [ 0.     36.9653  6.93    4.3   ]
 [ 0.     38.893  11.62    4.2   ]
 [ 0.     37.3773 10.53    4.8   ]
 [ 0.     35.8861 28.49    4.9   ]
 [ 0.     37.4635 15.29    4.3   ]
 [ 0.     37.0201 10.      4.1   ]
 [ 0.     37.6546  4.5     4.5   ]
 [ 0.     37.5318 17.58    4.6   ]
 [ 0.     39.0388  7.52    4.5   ]
 [ 0.     38.357  10.05    4.1   ]
 [ 0.     35.7018  6.25    4.1   ]
 [ 0.     37.6883 10.63    4.1   ]]


3. Display the row numbers where last values are equal to 4.5 or higher.

In [12]:
data3= np.where(data1[:,3]>=4.5) # get last cells from all rows and check 
print(data3)

(array([ 4,  6,  7, 10, 11, 14, 15, 16], dtype=int64),)


4. Assign 1 to first row.

In [13]:
data1[0]=1
print(data1)

[[ 1.      1.      1.      1.    ]
 [ 0.     37.4341  7.02    4.1   ]
 [ 0.     37.6878 10.27    4.4   ]
 [ 0.     37.2003 78.07    4.    ]
 [ 0.     35.6846 42.77    4.5   ]
 [ 0.     36.4171 14.86    4.1   ]
 [ 0.     36.0535 36.68    5.2   ]
 [ 0.     37.1958 50.33    4.8   ]
 [ 0.     36.9653  6.93    4.3   ]
 [ 0.     38.893  11.62    4.2   ]
 [ 0.     37.3773 10.53    4.8   ]
 [ 0.     35.8861 28.49    4.9   ]
 [ 0.     37.4635 15.29    4.3   ]
 [ 0.     37.0201 10.      4.1   ]
 [ 0.     37.6546  4.5     4.5   ]
 [ 0.     37.5318 17.58    4.6   ]
 [ 0.     39.0388  7.52    4.5   ]
 [ 0.     38.357  10.05    4.1   ]
 [ 0.     35.7018  6.25    4.1   ]
 [ 0.     37.6883 10.63    4.1   ]]


5. Save the final state of the array to disk. You are going to use this in the next assignment.

In [16]:
np.save("data1.npy",data1)
